version: '3'

services:
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml  # Mount file konfigurasi Prometheus
    networks:
      - eksperimen_sml_febhe

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks:
      - eksperimen_sml_febhe
    environment:
      GF_SECURITY_ADMIN_PASSWORD: 'admin'
    depends_on:
      - prometheus

networks:
  eksperimen_sml_febhe:
    driver: bridge

