name: Data Preprocessing and Docker Services

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Menjalankan setiap hari pada jam 00:00 UTC

jobs:
  preprocessing_and_docker:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.12
        options: --privileged
        ports:
          - 5000:5000
          - 9090:9090
          - 3000:3000

    steps:
      # Step 1: Check out the repository
      - name: Check out the repository
        uses: actions/checkout@v2

      # Step 2: Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Step 3: Set up Docker Compose
      - name: Install Docker Compose
        run: |
          curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      # Step 4: Set up Python (for preprocessing script)
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      # Step 5: Install Python dependencies
      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt

      # Step 6: Run the preprocessing script
      - name: Run preprocessing script
        run: |
          python preprocessing/automate_Febhe.py

      # Step 7: Build and start Docker containers (Flask, Prometheus, Grafana)
      - name: Build and start Docker containers
        run: |
          docker-compose up --build -d

      # Step 8: Check the status of the Docker containers
      - name: Check status of Docker containers
        run: |
          docker-compose ps

      # Step 9: Optionally, test the Flask metrics endpoint
      - name: Test Flask metrics endpoint
        run: |
          curl http://localhost:5000/metrics

