name: Data Preprocessing

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Menjalankan setiap hari pada jam 00:00 UTC

jobs:
  preprocessing:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run preprocessing script
      run: |
        python preprocessing/automate_Febhe.py
